apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "rafdir.labels" . | nindent 4 }}
  name: {{ include "rafdir.name" . }}
data:
  backblaze-application-key: {{ .Values.backblazeApplicationKey | b64enc | quote }}
  backblaze-key-id: {{ .Values.backblazeKeyId | b64enc | quote }}
  restic-repo-password: {{ .Values.repoPassword | b64enc | quote }}
