# This file contains a Role & RoleBinding for each namespace that the backup
# service should access and read PVCs from.{{- $namespaces := dict }}
{{- range $name, $profile := .Values.profiles }}
  {{- if not (empty $profile.namespace) }}
    {{- if not (hasKey $namespaces $profile.namespace) }}
      {{- $_ := set $namespaces $profile.namespace (dict "stop" false) }}
    {{- end }}

    {{- if and (hasKey $profile "stop") $profile.stop }}
      {{- $_ := set (index $namespaces $profile.namespace) "stop" true }}
    {{- end }}

    {{/* Detect any non-empty exec command */}}
    {{- $hasExec := false }}

    {{- range list "command-before" "command-after" }}
      {{- $cmd := index $profile . }}
      {{- if and (hasKey $profile .) (hasKey $cmd "cmd") (not (empty $cmd.cmd)) }}
        {{- $hasExec = true }}
        {{- break }}
      {{- end }}
    {{- end }}

    {{- if $hasExec }}
      {{- $_ := set (index $namespaces $profile.namespace) "exec" true }}
    {{- end }}
  {{- end }}
{{- end }}
{{- $root := . }}
{{- range $namespace, $nsData := $namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rafdir.name" $root }}
  namespace: {{ $namespace }}
  labels:
    {{- include "rafdir.labels" $root | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - persistentvolumeclaims
    verbs:
      - get
      - list
  {{- if $nsData.exec }}
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  {{- end }}
  # Read deployments
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
  {{- if $nsData.stop }}
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update"]
  {{- end }}
  - apiGroups:
      - "snapshot.storage.k8s.io"
    resources:
      - volumesnapshots
    verbs:
      - get
      - list
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rafdir.name" $root }}
  namespace: {{ $namespace }}
  labels:
    {{- include "rafdir.labels" $root | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rafdir.name" $root }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rafdir.name" $root }}
    namespace: {{ $root.Release.Namespace }}
---
{{- end }}
