kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "rafdir.name" . }}
  labels:
    {{- include "rafdir.labels" . | nindent 4}}
provisioner: driver.longhorn.io
allowVolumeExpansion: false
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
