apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resticprofile-kubernetes.name" . }}
  labels:
    {{- include "resticprofile-kubernetes.labels" . | nindent 4 }}
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resticprofile-kubernetes.name" . }}
  labels:
    {{- include "resticprofile-kubernetes.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "resticprofile-kubernetes.name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "resticprofile-kubernetes.name" . }}
    namespace: {{ .Release.Namespace }}
