apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "resticprofile-kubernetes.labels" . | nindent 4 }}
  name: {{ include "resticprofile-kubernetes.name" . }}-config
data:
  profiles.yaml: |
    {{- index .Values "profiles.yaml" | nindent 4 }}

  profiles: |
    {{- .Values.profiles | toYaml | nindent 4 }}
