apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "resticprofile-kubernetes.labels" . | nindent 4 }}
  name: {{ include "resticprofile-kubernetes.name" . }}-config
data:
  profiles.yaml: |
    {{- .Values.profiles | nindent 4 }}
