apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "resticprofile-kubernetes.name" . }}
  labels:
    {{- include "resticprofile-kubernetes.labels" . | nindent 4}}
spec:
  # Cron schedule that runs once a day
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "resticprofile-kubernetes.name" . }}
          containers:
          - name: resticprofile-kubernetes
            image: "ghcr.io/javex/resticprofile-kubernetes:latest"
            imagePullPolicy: Always
          restartPolicy: Never
