apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resticprofile-kubernetes.name" . }}
  labels:
    {{- include "resticprofile-kubernetes.labels" . | nindent 4 }}
automountServiceAccountToken: true
